version: '3'

services:

  f1-be:
    image: 91kovacsk/f1-be
    container_name: f1-be-cont
    environment:
      NODE_DBHOST: ${NODE_DBHOST}
      S_SEC: ${S_SEC}
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - f1-net
    depends_on:
      - sqledge

  f1-fe:
    image: 91kovacsk/f1-fe
    container_name: f1-fe-cont
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - f1-net
    depends_on:
      - f1-be

  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: f1-sqledge
    command: /opt/mssql/bin/sqlservr
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "notPassword123"
    stdin_open: true
    ports:
      - "1433:1433"
    volumes:
      - ../f1-data/SQLEDGE/data:/var/opt/sqledge/data
      - ../f1-data/SQLEDGE/log:/var/opt/sqledge/log
      - ../f1-data/SQLEDGE/secrets:/var/opt/sqledge/secrets
    networks:
      - f1-net

  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    command: /opt/mssql_scripts/import-data.sh
    stdin_open: true
    volumes:
      - ./data/mssql_scripts:/opt/mssql_scripts
    networks:
      - f1-net
      
networks:
  f1-net:
    driver: bridge